name: 'Terraform Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{secrets.AWS_ID}}'
          aws-secret-access-key: '${{$AWS_SECRET}}'
          aws-region: us-east-1