name: 'Terraform Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  terraform_checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Terraform
      env:
            TERRAFORM_VERSION: "0.12.15"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
    - uses: actions/checkout@v1
    - name: Terrafrom plan
      env:
            TERRAFORM_VERSION: "0.12.15"
      run: |
        terraform plan